<a href="https://colab.research.google.com/github/Archangel212/ConSinGAN/blob/master/ConSinGAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import UpSampling2D
import numpy as np
import torch
import PIL


In [ ]:
X = np.array([[1,2],[3,4]])
X = X.reshape((1,2,2,1))
model = Sequential()
model.add(UpSampling2D(input_shape=(2,2,1)))
output = model.predict(X)
print(model.summary())
output.shape

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_12 (UpSampling (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
None


(1, 4, 4, 1)

In [ ]:
output.resize((4,4))
print(output)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [ ]:
# example of using upsampling in a simple generator model
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import Conv2D
# define model
model = Sequential()
# define input shape, output enough activations for for 128 5x5 image
model.add(Dense(128 * 5 * 5, input_dim=1))
# reshape vector of activations into 128 feature maps with 5x5
model.add(Reshape((5, 5, 128)))
# double input from 128 5x5 to 1 10x10 feature map
model.add(UpSampling2D())
# fill in detail in the upsampled feature maps and output a single image
model.add(Conv2D(1, (3,3), padding="same"))
# summarize model
model.summary()

# X = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
# X = X.reshape((1,5,5,1))
# print(X.shape)
# model.predict(X)

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 3200)              6400      
_________________________________________________________________
reshape_5 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_7 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 10, 10, 1)         1153      
Total params: 7,553
Trainable params: 7,553
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# X = [ [0,0,0,0,0,0,0,0,0],
#       [0,0,0,0,0,0,0,0,0],
#      [0,0,  1,0,1,0,2,  0,0],
#      [0,0,  1,1,3,2,1,  0,0],
#      [0,0,  1,1,0,1,1,  0,0],
#      [0,0,  2,3,2,1,3,  0,0],
#      [0,0,  0,2,0,1,0,  0,0],
#       [0,0,0,0,0,0,0,0,0],
#       [0,0,0,0,0,0,0,0,0]]

X = [[1,0,1,0,2],
     [1,1,3,2,1],
     [1,1,0,1,1],
     [2,3,2,1,3],
     [0,2,0,1,0]]

kernel = [[0,3,0],
          [0,0,2],
          [0,1,0]]

def transposed2D(X, kernel, padding="full", stride=1):
  X = X if type(X) is np.array else np.array(X)
  kernel = kernel if type(kernel) is np.array else np.array(kernel)

  if padding == "full":
    X = np.pad(X, 2)
    pad = 2
  elif padding == "half":
    X = np.pad(X, 1)
    pad = 1
  else:
    X = X
    pad = 0
  
  #kernel flip
  kernel = np.array([k[::-1] for k in reversed(kernel)]) 

  H_X, W_X = X.shape
  H_Kernel, W_Kernel = kernel.shape
  print(X, H_X, W_X,H_Kernel,W_Kernel)
  print(kernel,(H_X + 2*pad - H_Kernel // stride) + 1)
  for H in range((H_X + 2*pad - H_Kernel // stride) + 1):
    print(H)
transposed2D(X, kernel, padding="full")


[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 2 0 0]
 [0 0 1 1 3 2 1 0 0]
 [0 0 1 1 0 1 1 0 0]
 [0 0 2 3 2 1 3 0 0]
 [0 0 0 2 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]] 9 9 3 3
[[0 1 0]
 [2 0 0]
 [0 3 0]] 11
0
1
2
3
4
5
6
7
8
9
10


In [ ]:
i = torch.randn(1,1,64,64)
class Net(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = torch.nn.Conv2d(1,32,5)
    self.conv2 = torch.nn.Conv2d(32,64,5)
    self.conv3 = torch.nn.Conv2d(64,128,5)
    self.max1 = torch.nn.MaxPool2d((2,2))
    self.max2 = torch.nn.MaxPool2d((2,2))
    self.max3 = torch.nn.MaxPool2d((2,2))

    self.fc1 = torch.nn.Linear(2048,2048)
    self.fc2 = torch.nn.Linear(2048,2)

    for key in vars(self).keys():print(key)
  def forward(self, x):
    # x = torch.nn.ReLU(self.conv1(X))
    x = self.max1(torch.nn.functional.relu(self.conv1(x)))
    x = self.max2(torch.nn.functional.relu(self.conv2(x)))
    x = self.max3(torch.nn.functional.relu(self.conv3(x)))
    print(x.flatten(start_dim=1).shape)

    x = x.flatten(start_dim=1)
    x = self.fc1(x)
    x = self.fc2(x)

net = Net()
net(i)

training
_parameters
_buffers
_backward_hooks
_forward_hooks
_forward_pre_hooks
_state_dict_hooks
_load_state_dict_pre_hooks
_modules
torch.Size([1, 2048])


{'In': ['',
  'import keras\nfrom keras.models import Sequential\nfrom keras.layers import UpSampling2D\nimport numpy as np\nimport torch',
  'vars()'],
 'Out': {},
 'Sequential': keras.engine.sequential.Sequential,
 'UpSampling2D': keras.layers.convolutional.UpSampling2D,
 '_': '',
 '__': '',
 '___': '',
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__loader__': None,
 '__name__': '__main__',
 '__package__': None,
 '__spec__': None,
 '_dh': ['/content'],
 '_i': 'import keras\nfrom keras.models import Sequential\nfrom keras.layers import UpSampling2D\nimport numpy as np\nimport torch',
 '_i1': 'import keras\nfrom keras.models import Sequential\nfrom keras.layers import UpSampling2D\nimport numpy as np\nimport torch',
 '_i2': 'vars()',
 '_ih': ['',
  'import keras\nfrom keras.models import Sequential\nfrom keras.layers import UpSampling2D\nimport numpy as 

In [ ]:
# Install useful stuff
! apt install --yes ssh screen nano htop ranger git > /dev/null# SSH setting
! echo "root:carbonara" | chpasswd
! echo "PasswordAuthentication yes" > /etc/ssh/sshd_config
! echo "PermitUserEnvironment yes" >> /etc/ssh/sshd_config
! echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
! service ssh restart > /dev/null # Download ngrok
! wget -q -c -nc https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
! unzip -qq -n ngrok-stable-linux-amd64.zip # Run ngrok
authtoken = "1fRJ3ewU6MdRxFBmsSF8L6u7fr4_3rLU929ZzgsjspGKSNyiT"
get_ipython().system_raw('./ngrok authtoken $authtoken && ./ngrok tcp 22 &')
! sleep 3# Get the address for SSH
import requests
from re import sub
r = requests.get('http://localhost:4040/api/tunnels')
str_ssh = r.json()['tunnels'][0]['public_url']
str_ssh = sub("tcp://", "", str_ssh)
str_ssh = sub(":", " -p ", str_ssh)
str_ssh = "ssh root@" + str_ssh
print(str_ssh)




E: Unable to locate package SSH
E: Unable to locate package setting
ssh: unrecognized service
sleep: invalid time interval ‘3#’
sleep: invalid time interval ‘Get’
sleep: invalid time interval ‘the’
sleep: invalid time interval ‘address’
sleep: invalid time interval ‘for’
sleep: invalid time interval ‘SSH’
Try 'sleep --help' for more information.
ssh root@2.tcp.ngrok.io -p 19595


In [ ]:
def run_forever():
  i = 0
  while(True):
    i+=1


!pip install colab_ssh --upgrade
ngrokToken="1fRJ3ewU6MdRxFBmsSF8L6u7fr4_3rLU929ZzgsjspGKSNyiT"
password="skripsi"
from colab_ssh import launch_ssh, init_git
launch_ssh(ngrokToken,password)
run_forever()


Requirement already up-to-date: colab_ssh in /usr/local/lib/python3.6/dist-packages (0.2.63)
Successfully running 0.tcp.ngrok.io:19517
[Optional] You can also connect with VSCode SSH Remote extension using this configuration:

	Host google_colab_ssh
		HostName 0.tcp.ngrok.io
		User root
		Port 19517
	  


KeyboardInterrupt: ignored

In [ ]:
!git config --global user.name "Archangel212"
!git config --global user.email "michaeldavidbaskoro@gmail.com" 
!git clone https://github.com/Archangel212/cnn-mrf-cloned.git
%cd cnn-mrf-cloned

Cloning into 'cnn-mrf-cloned'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 33 (delta 6), reused 32 (delta 5), pack-reused 0
Unpacking objects: 100% (33/33), done.
/content/cnn-mrf-cloned


In [ ]:
!ls
!python3 main.py --content_path ./data/content1.jpg --style_path ./data/style1.jpg


data  main.py  model.py  mylibs.py  progress  README.md
Namespace(content_path='./data/content1.jpg', content_weight=1, gpu_chunck_size=512, max_iter=100, mrf_style_stride=2, mrf_synthesis_stride=2, num_res=3, progress_path='./progress', sample_step=50, style_path='./data/style1.jpg', style_weight=0.4, tv_weight=0.1)
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3000: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and uses scale_factor directly, instead of relying on the computed output size. If you wish to keep the old beha

In [ ]:
import datetime
import pytz

utc_now = pytz.utc.localize(datetime.datetime.now())
wib_now = utc_now.astimezone(pytz.timezone("Asia/Jakarta"))
print(wib_now.strftime("%A_%d-%B-%Y_%H:%M:%S"), utc_now.strftime("%A_%d-%B-%Y_%H:%M:%S"))

# !git remote set-url origin https://Archangel212:fibonacci382618@github.com/Archangel212/cnn-mrf-cloned.git
# !git add .
# !git commit -m "Updating training progress at $now"
# !git push origin master

Friday_02-October-2020_18:30:43 Friday_02-October-2020_11:30:43


In [ ]:
import matplotlib.pyplot as plt
import PIL
import torchvision
import torch
import os
from shutil import copyfile

In [ ]:
sample_name = "Batik_188.jpg"
sample_path = "/content/drive/My Drive/Batik Images/Resized_Batik_Images_500by500/" + sample_name

pil_image = PIL.Image.open(sample_path)
tensor_image = torchvision.transforms.ToTensor()(pil_image)
plt.imshow(pil_image), tensor_image.shape

In [ ]:
!git config --global user.name "Archangel212"
!git config --global user.email "michaeldavidbaskoro@gmail.com" 
# !git clone https://github.com/Archangel212/SinGAN.git
!git clone -b foldername-configs  https://github.com/Archangel212/SinGAN.git

# !git remote set-url origin https://Archangel212:fibonacci382618@github.com/Archangel212/SinGAN.git

In [ ]:
# copyfile(sample_path,"/content/SinGAN/Input/Images/" + sample_name )
# %cd /content/SinGAN
# !python -m pip install -r requirements.txt
# !python main_train.py --input_name $sample_name --scale_factor 0.65 --alpha 8

In [ ]:
!python random_samples.py --input_name $sample_name --mode random_samples --gen_start_scale 

In [ ]:
!git add .
!git commit -m "Training and generating random $sample_name scale_factor 0.65 and alpha 8 "
# !git commit -m "Training $sample_name with alpha 10"
!git remote set-url origin https://Archangel212:fibonacci382618@github.com/Archangel212/SinGAN.git
!git push origin master